>compound 4,5-Dicaffeoyl quinic acid
>formula C25H24O12
>ionization [M+H]+
>parentmass 517.1340526600904
#inchi InChI=1S/C25H24O12/c26-15-5-1-13(9-17(15)28)3-7-21(31)36-20-12-25(35,24(33)34)11-19(30)23(20)37-22(32)8-4-14-2-6-16(27)18(29)10-14/h1-10,19-20,23,26-30,35H,11-12H2,(H,33,34)/b7-3+,8-4+/t19-,20-,23-,25+/m1/s1
#inchikey UFCLZKMFXSILNL
#Ion_Source LC-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 517.1
#ExactMass 516.127
#Charge 1
#CAS_Number 89886-31-7
#Pubmed_ID N/A
#Smiles O[C@@H]1C[C@@](O)(C(O)=O)C[C@@H](OC(/C=C/C2=CC=C(O)C(O)=C2)=O)[C@@H]1OC(/C=C/C3=CC=C(O)C(O)=C3)=O
#INCHI_AUX N/A
#Library_Class 3
#SpectrumID CCMSLIB00000081758
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 445bf109b7eb4fc091fb6c19942b2a28
##Scan# 1
#SpectrumFile gnps_4_5_Dicaffeoylquinic_acid_pos_MplusH.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism batch_27_05_V03
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 517.1
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 10
145.030563 8.0
163.041885 299.0
319.090912 6.0
337.096283 7.0
499.129303 17.0
