>compound 2-hydroxy-3-(3-hydroxy-3-methylbutyl)naphthalene-1,4-dione
>formula C15H16O4
>ionization [M+Na]+
>parentmass 283.092499
#inchi InChI=1S/C15H16O4/c1-15(2,19)8-7-11-12(16)9-5-3-4-6-10(9)13(17)14(11)18/h3-6,18-19H,7-8H2,1-2H3
#inchikey OVRABUAZHGSQBY
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Niege Furtado
#Scan -1
#Precursor_MZ 283.092
#ExactMass 260.105
#Charge 1
#CAS_Number  
#Pubmed_ID  
#Smiles O=C1C(CCC(C)(O)C)=C(O)C(C2=CC=CC=C21)=O
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081263
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID ff3f3374d2214e088786d6ba9efca32f
##Scan# 1
#SpectrumFile gnps_2_hydroxy_3_3_hydroxy_3_methylbutyl_naphthalene_1_4_dione_pos_MplusNa.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 283.092
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 10
209.017456 101191.0
210.020737 12690.0
211.024017 1013.0
224.326569 681.0
224.718246 681.0
227.03009 3036.0
265.081085 18371.0
283.092499 24733.0
