>compound Caffeic acid
>formula C9H8O4
>ionization [M+H]+
>parentmass 181.04953518809054
#inchi InChI=1S/C9H8O4/c10-7-3-1-6(5-8(7)11)2-4-9(12)13/h1-5,10-11H,(H,12,13)/b4-2+
#inchikey QAIPRVGONGVQAS
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Commercial
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 181.044
#ExactMass 180.042
#Charge 1
#CAS_Number 331-39-5
#Pubmed_ID  
#Smiles OC1=C(O)C=C(/C=C/C(O)=O)C=C1
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000078847
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID dcfc54b36cdf4397835f959bddb4f679
##Scan# 1
#SpectrumFile caffeic_acid_pos_MSMS_181.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 181.044
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 10
117.03125 135.0
135.040268 1489.0
139.057632 108.0
145.02446 1033.0
163.033752 29106.0
164.038986 1442.0
181.043823 1433.0
