>compound Gallic acid
>formula C7H6O5
>ionization [M+H]+
>parentmass 171.027985
#inchi InChI=1S/C7H6O5/c8-4-1-3(7(11)12)2-5(9)6(4)10/h1-2,8-10H,(H,11,12)
#inchikey LNTHITQWFMADLM
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Commercial
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 171.028
#ExactMass 170.021
#Charge 1
#CAS_Number 149-91-7
#Pubmed_ID  
#Smiles OC(C1=CC(O)=C(O)C(O)=C1)=O
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000078850
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID f53f249df66b417496cba5eb33e64332
##Scan# 1
#SpectrumFile gallic_acid_pos_MSMS_171.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 171.028
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 10
125.021797 2601.0
126.026176 143.0
127.037621 786.0
135.006775 598.0
143.031845 325.0
153.017792 5492.0
154.024673 273.0
171.027985 631.0
