>compound 3,4-dihydro-2,2-dimethyl-indeno[1,2-b]-pyran-5(2H)-one
>formula C14H14O2
>ionization [M+H]+
>parentmass 215.10665614009054
#inchi InChI=1S/C14H14O2/c1-14(2)8-7-11-12(15)9-5-3-4-6-10(9)13(11)16-14/h3-6H,7-8H2,1-2H3
#inchikey ICNOFNFXLJFTLZ
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Niege Furtado
#Scan -1
#Precursor_MZ 159.04
#ExactMass 214.099
#Charge 1
#CAS_Number 1027802-08-9
#Pubmed_ID  
#Smiles CC(CC1)(C)OC(C2=CC=CC=C23)=C1C3=O
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081254
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 57fbd2b28d364df6847e5b8573742fe8
##Scan# 1
#SpectrumFile gnps_3_4_dihydro_2_2_dimethyl_indeno_1_2_b_pyran_5_2H_one_pos_MplusHminus56.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 159.04
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 10
116.974312 249.0
127.070312 111.0
131.045715 1787.0
132.049347 188.0
133.026154 134.0
139.067474 107.0
159.040421 5027.0
