>compound Nigrosporapyrone D
>formula C8H8O4
>ionization [M+H]+
>parentmass 169.050446
#inchi InChI=1S/C8H8O4/c1-5(9)7-3-6(11-2)4-8(10)12-7/h3-4H,1-2H3
#inchikey MELHVRFNTXYFMN
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Monica Pupo
#Scan -1
#Precursor_MZ 169.05
#ExactMass 168.042
#Charge 1
#CAS_Number 1147548-14-8
#Pubmed_ID N/A
#Smiles O=C1C=C(OC)C=C(C(C)=O)O1
#INCHI_AUX N/A
#Library_Class 3
#SpectrumID CCMSLIB00000081749
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 52bd5f0db6314c93924d5ce5c86348eb
##Scan# 1
#SpectrumFile gnps_NigrosporapyroneD_pos_MplusH.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism batch_27_05_V02
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 169.05
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 10
95.016708 180.0
99.04776 528.0
109.02697 100.0
127.039062 1674.0
169.050446 1923.0
170.05275 119.0
