>compound 9,10-alpha-Epoxy-eremanthin
>formula C15H18O3
>ionization [M+Na]+
>parentmass 269.1148151360905
#inchi InChI=1S/C15H18O3/c1-7-4-5-10-12(7)13-9(8(2)14(16)17-13)6-11-15(10,3)18-11/h9-13H,1-2,4-6H2,3H3/t9-,10+,11+,12-,13-,15-/m0/s1
#inchikey JFFHVIUZNPTGGR
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 269.073
#ExactMass 246.126
#Charge 1
#CAS_Number 38963-61-0
#Pubmed_ID  
#Smiles [H][C@@]1(CCC2=C)[C@@]2([H])[C@@H](OC(C3=C)=O)[C@H]3C[C@@H]4[C@]1(O4)C
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081306
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID dc0208ee96f840bfb92a750ad83003c7
##Scan# 1
#SpectrumFile gnps_9_10_a_Epoxy_eremanthin_pos_MplusNa.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 269.073
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 10
145.067657 124.0
152.0578 147.0
167.029297 164.0
226.054092 1707.0
227.057007 108.0
254.049286 269.0
269.07251 1148.0
