>compound 2,2-dimethyl-5-oxo-2,3,4,5-tetrahydroindeno[1,2-b]pyran-6-carboxylic acid
>formula C15H14O4
>ionization [M+Na]+
>parentmass 281.07842962809053
#inchi InChI=1S/C15H14O4/c1-15(2)7-6-10-12(16)11-8(13(10)19-15)4-3-5-9(11)14(17)18/h3-5H,6-7H2,1-2H3,(H,17,18)
#inchikey SRAZIDLUTMRWNZ
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Niege Furtado
#Scan -1
#Precursor_MZ 281.073
#ExactMass 258.089
#Charge 1
#CAS_Number  
#Pubmed_ID  
#Smiles CC(CC1)(C)OC(C2=CC=CC(C(O)=O)=C23)=C1C3=O
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081248
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 58a4ace7fefd4f8ba9ca99d01553ac72
##Scan# 1
#SpectrumFile gnps_2_2_dimethyl_5_oxo_2_3_4_5_tetrahydroindeno_1_2_b_pyran_6_carboxylic_acid_pos_M_Na.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 281.073
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
121.061 21.95
129.0296 2.0
149.0199 19.66
173.0917 9.41
181.0246 1.98
281.0784 0.0
