>compound Mangiferin
>formula C19H18O11
>ionization [M+H]+
>parentmass 423.09218784809053
#inchi InChI=1S/C19H18O11/c20-4-11-15(25)17(27)18(28)19(30-11)12-8(23)3-10-13(16(12)26)14(24)5-1-6(21)7(22)2-9(5)29-10/h1-3,11,15,17-23,25-28H,4H2/t11-,15-,17+,18-,19+/m1/s1
#inchikey AEDDIBAIWPIIBD
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Commercial
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 423.09
#ExactMass 422.085
#Charge 1
#CAS_Number 4773-96-0
#Pubmed_ID  
#Smiles OC[C@@H]1[C@@H](O)[C@H](O)[C@@H](O)[C@H](C2=C(O)C3=C(C=C2O)OC4=CC(O)=C(O)C=C4C3=O)O1
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000078863
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 9b50b8bdd520421f83e2b4c8db97d5db
##Scan# 1
#SpectrumFile mangiferin_pos_MSMS_423.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 423.09
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
261.037 5.45
313.0695 7.67
423.0922 0.0
