>compound Kaempferol
>formula C15H10O6
>ionization [M+H]+
>parentmass 287.05501449209055
#inchi InChI=1S/C15H10O6/c16-8-3-1-7(2-4-8)15-14(20)13(19)12-10(18)5-9(17)6-11(12)21-15/h1-6,16-18,20H
#inchikey IYRMWMYZSQPJKC
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Commercial
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 287.047
#ExactMass 286.048
#Charge 1
#CAS_Number 520-18-3
#Pubmed_ID  
#Smiles O=C1C2=C(C=C(C=C2OC(C3=CC=C(C=C3)O)=C1O)O)O
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000078877
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 09d793c0e0ad47e3a1cb90cea12cd007
##Scan# 1
#SpectrumFile gnps_kaempferol_pos_MSMS_287.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 287.047
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
119.0477 1.11
155.0547 3.14
195.0435 1.55
287.055 0.0
