>compound Gibberellic acid
>formula C19H22O6
>ionization [M+H]+
>parentmass 347.14891487609054
#inchi InChI=1S/C19H22O6/c1-9-7-17-8-18(9,24)5-3-10(17)19-6-4-11(20)16(2,15(23)25-19)13(19)12(17)14(21)22/h4,6,10-13,20,24H,1,3,5,7-8H2,2H3,(H,21,22)/t10-,11+,12-,13-,16-,17+,18+,19-/m1/s1
#inchikey IXORZMNAPKEEDV
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Commercial
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 347.155
#ExactMass 346.142
#Charge 1
#CAS_Number 77-06-5
#Pubmed_ID  
#Smiles C=C1C[C@@]23[C@@H](C(O)=O)[C@]4([H])[C@@]5(C)[C@@H](O)C=C[C@@]4(OC5=O)[C@]2([H])CC[C@]1(O)C3
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081270
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 94dd531c4d8241d0b25a287f981bad78
##Scan# 1
#SpectrumFile gnps_Gibberellic_acid_pos_MplusH.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 347.155
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
145.1001 0.56
165.0746 0.69
180.099 1.19
181.102 0.66
195.1212 0.83
221.1362 9.26
222.1395 0.98
239.1494 60.22
240.1523 8.32
347.1489 0.0
