>compound Luteolin
>formula C15H10O6
>ionization [M+H]+
>parentmass 287.05501449209055
#inchi InChI=1S/C15H10O6/c16-8-4-11(19)15-12(20)6-13(21-14(15)5-8)7-1-2-9(17)10(18)3-7/h1-6,16-19H
#inchikey IQPNAANSBPBGFQ
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Commercial
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 287.046
#ExactMass 286.048
#Charge 1
#CAS_Number 491-70-3
#Pubmed_ID  
#Smiles O=C1C2=C(C=C(C=C2OC(C3=CC=C(C(O)=C3)O)=C1)O)O
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000078878
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID a7811c4bf87d4994841200bf262634c1
##Scan# 1
#SpectrumFile gnps_luteolin_pos_MSMS_287.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 287.046
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
131.0474 0.95
172.0379 0.88
287.055 0.0
