>compound Hesperedin
>formula C28H34O15
>ionization [M+H]+
>parentmass 611.1970468400905
#inchi InChI=1S/C28H34O15/c1-10-21(32)23(34)25(36)27(40-10)39-9-19-22(33)24(35)26(37)28(43-19)41-12-6-14(30)20-15(31)8-17(42-18(20)7-12)11-3-4-16(38-2)13(29)5-11/h3-7,10,17,19,21-30,32-37H,8-9H2,1-2H3/t10-,17-,19+,21-,22+,23+,24-,25+,26+,27+,28+/m0/s1
#inchikey QUQPHWDTPGMPEX
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 611.172
#ExactMass 610.19
#Charge 1
#CAS_Number 520-26-3
#Pubmed_ID  
#Smiles O=C1C2=C(O)C=C(O[C@H]3[C@H](O)[C@@H](O)[C@H](O)[C@@H](CO[C@@H]4O[C@@H](C)[C@H](O)[C@@H](O)[C@H]4O)O3)C=C2O[C@H](C5=CC=C(OC)C(O)=C5)C1
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000077991
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 974ef4cf58c742779f68f9e14e4ae1ff
##Scan# 1
#SpectrumFile gnps_hesperedin_pos_MSMS2_611.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 611.172
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
303.0681 100.0
345.0768 7.43
369.074 2.85
395.0893 0.68
413.0988 7.03
431.1092 7.73
449.1201 11.18
611.197 0.0
