>compound Baicalein
>formula C15H10O5
>ionization [M+H]+
>parentmass 271.0600998720905
#inchi InChI=1S/C15H10O5/c16-9-6-11(8-4-2-1-3-5-8)20-12-7-10(17)14(18)15(19)13(9)12/h1-7,17-19H
#inchikey FXNFHKRTJBSTCS
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Commercial
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 271.055
#ExactMass 270.053
#Charge 1
#CAS_Number 491-67-8
#Pubmed_ID  
#Smiles O=C1C2=C(O)C(O)=C(O)C=C2OC(C3=CC=CC=C3)=C1
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000078872
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID e7446cf64da740c6a68bb81a7292e098
##Scan# 1
#SpectrumFile gnps_baicalein_pos_MSMS_271.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 271.055
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
119.048 0.99
131.0483 0.87
271.0601 0.0
