>compound Ethyl 1-cyclopropyl-6,7-difluoro-8-methoxy-4-oxo-1,4-dihydro-3-quinolinecarboxylate
>formula C16H15F2NO4
>ionization [M+Na]+
>parentmass 346.08613510009053
#inchi InChI=1S/C16H15F2NO4/c1-3-23-16(21)10-7-19(8-4-5-8)13-9(14(10)20)6-11(17)12(18)15(13)22-2/h6-8H,3-5H2,1-2H3
#inchikey XPAOPAPDCRLMTR
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Commercial
#PI Norberto Lopes
#Data_Collector Norberto Lopes
#Scan -1
#Precursor_MZ 346.082
#ExactMass 323.097
#Charge 1
#CAS_Number 112811-71-9
#Pubmed_ID N/A
#Smiles COC1=C2C(C(C(C(OCC)=O)=CN2C3CC3)=O)=CC(F)=C1F
#INCHI_AUX N/A
#Library_Class 3
#SpectrumID CCMSLIB00000081586
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 4a07f16a650f4095b43fe6b0b09ff8bb
##Scan# 1
#SpectrumFile gnps_Ethyl_1_cyclopropyl_6_7_difluoro_8_methoxy_4_oxo_1_4_dihydro_3_quinolinecarboxylate_pos_MplusNa.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism batch_27_05
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 346.082
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
275.0281 19.34
276.0386 17.97
290.0202 32.42
346.0861 0.0
