>compound Maytenin
>formula C28H36O3
>ionization [M+H]+
>parentmass 421.2737214640905
#inchi InChI=1S/C28H36O3/c1-16-13-23-25(3,15-21(16)30)9-11-27(5)22-8-7-18-17(2)24(31)20(29)14-19(18)26(22,4)10-12-28(23,27)6/h7-8,14,16,23,31H,9-13,15H2,1-6H3/t16-,23?,25+,26+,27-,28+/m1/s1
#inchikey WSTYNZDAOAEEKG
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 421.271
#ExactMass 420.266
#Charge 1
#CAS_Number 50802-21-6
#Pubmed_ID  
#Smiles O=C1C[C@]2(C)CC[C@]3(C)C([C@@]4(C)CC[C@@]3(C)C2C[C@H]1C)=CC=C(C4=C5)C(C)=C(O)C5=O
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000078862
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID acbd33f8eb6b4930835f1b1ae09fbdef
##Scan# 1
#SpectrumFile maytenin_pos_MSMS_421.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 421.271
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
163.1098 0.26
215.1056 14.07
219.1729 2.51
233.1893 3.15
241.1208 1.85
403.2595 1.24
421.2705 17.07
