>compound Altertoxin I
>formula C20H16O6
>ionization [M+H-H2O]+
>parentmass 335.091187
#inchi InChI=1S/C20H16O6/c21-10-3-1-8-9-2-4-11(22)17-12(23)5-6-20(26,18(9)17)19-14(25)7-13(24)16(10)15(8)19/h1-4,14,19,21-22,25-26H,5-7H2/t14-,19+,20-/m0/s1
#inchikey GJIALGLHOBXNAT
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Monica Pupo
#Scan -1
#Precursor_MZ 335.091
#ExactMass 352.095
#Charge 1
#CAS_Number 56258-32-3
#Pubmed_ID N/A
#Smiles OC(C=C1)=C(C2=C1C3=CC=C(O)C(C(CC4)=O)=C3[C@]4(O)[C@]2([H])[C@@H](O)C5)C5=O
#INCHI_AUX N/A
#Library_Class 3
#SpectrumID CCMSLIB00000081751
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 52bd5f0db6314c93924d5ce5c86348eb
##Scan# 1
#SpectrumFile gnps_AltertoxinI_pos_MplusHminusH2O.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism batch_27_05_V02
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 335.091
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
247.0742 20.04
275.0695 32.42
291.0632 100.0
307.0963 42.24
335.0912 91.75
