>compound (2R,3R,4S,6R)-2-((5-hydroxy-2,2-dimethyl-3,4-dihydro-2H-benzo[h]chromen-6-yl)oxy)-6-(hydroxymethyl)tetrahydro-2H-pyran-3,4,5-triol
>formula C21H26O8
>ionization [M+H]+
>parentmass 407.1700442440905
#inchi InChI=1S/C21H26O8/c1-21(2)8-7-12-14(23)19(11-6-4-3-5-10(11)18(12)29-21)28-20-17(26)16(25)15(24)13(9-22)27-20/h3-6,13,15-17,20,22-26H,7-9H2,1-2H3/t13-,15?,16+,17-,20-/m1/s1
#inchikey WVILKFILAZPSRT
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Niege Furtado
#Scan -1
#Precursor_MZ 407.166
#ExactMass 406.163
#Charge 1
#CAS_Number  
#Pubmed_ID  
#Smiles OC1=C(O[C@H]2O[C@H](CO)C(O)[C@H](O)[C@H]2O)C3=CC=CC=C3C4=C1CCC(C)(C)O4
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081257
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 3471945c40b7425b810acbce60284eb4
##Scan# 1
#SpectrumFile gnps_2S_3S_4R_6S_2_6_hydroxy_2_2dimethyl_3_4_dihydro_2H_benzo_h_chromen-5-yl_oxy_6_hydroxymethyl_tetrahydro_2H_pyran_3_4_5_triol_pos_MplusH.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 407.166
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
121.063 0.7
199.1106 6.33
227.1053 21.54
245.1149 100.0
407.1661 2.97
