>compound Naringenin_pos
>formula C15H12O5
>ionization [M+H]+
>parentmass 273.0757499360905
#inchi InChI=1S/C15H12O5/c16-9-3-1-8(2-4-9)13-7-12(19)15-11(18)5-10(17)6-14(15)20-13/h1-6,13,16-18H,7H2
#inchikey FTVWIRXFELQLPI
#Ion_Source DI-ESI
#Instrument Ion Trap
#Compound_Source Commercial
#PI Norberto
#Data_Collector Denise
#Scan -1
#Precursor_MZ 273.0
#ExactMass 272.069
#Charge 1
#CAS_Number 67604-48-2
#Pubmed_ID  
#Smiles O=C1C2=C(C=C(C=C2OC(C1)C3=CC=C(C=C3)O)O)O
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000077218
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 919473c07bef4632b021011afb965ddc
##Scan# 1
#SpectrumFile gnps_Naringenin_pos_amp0.5V_MSMS_273.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 273
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
111.008 0.85
121.101 1.3
207.029 3.56
273.0757 0.0
