>compound 3-O-??-(6???-trans-caffeoyl)-galactopyranosyl quercetin
>formula C30H26O15
>ionization [M+Na]+
>parentmass 649.1163908320905
#inchi InChI=1S/C30H26O15/c31-14-9-19(36)23-20(10-14)43-28(13-3-5-16(33)18(35)8-13)29(25(23)39)45-30-27(41)26(40)24(38)21(44-30)11-42-22(37)6-2-12-1-4-15(32)17(34)7-12/h1-10,21,24,26-27,30-36,38,40-41H,11H2/b6-2+/t21-,24+,26+,27-,30+/m0/s1
#inchikey IHBVMUCQCZEAPW
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 649.062
#ExactMass 626.127
#Charge 1
#CAS_Number 84575-22-4
#Pubmed_ID N/A
#Smiles OC1=C(O)C=C(C2=C(O[C@H]3O[C@@H](COC(/C=C/C4=CC=C(O)C(O)=C4)=O)[C@@H](O)[C@@H](O)[C@@H]3O)C(C5=C(O)C=C(O)C=C5O2)=O)C=C1
#INCHI_AUX N/A
#Library_Class 3
#SpectrumID CCMSLIB00000081698
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 52bd5f0db6314c93924d5ce5c86348eb
##Scan# 1
#SpectrumFile gnps_3_O_beta_6_trans_caffeoyl_galactopiranosyl_quercetin_pos_MplusNa.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism batch_27_05_V02
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 649.062
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
163.023 9.04
324.9998 18.13
347.0429 100.0
649.1164 0.0
