>compound Licarin A
>formula C20H22O4
>ionization [M+H]+
>parentmass 327.15908563609054
#inchi InChI=1S/C20H22O4/c1-5-6-13-9-15-12(2)19(24-20(15)18(10-13)23-4)14-7-8-16(21)17(11-14)22-3/h5-12,19,21H,1-4H3/b6-5+
#inchikey ITDOFWOJEDZPCF
#Ion_Source DI-ESI
#Instrument Ion Trap
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 327.3
#ExactMass 326.152
#Charge 1
#CAS_Number 51020-86-1
#Pubmed_ID  
#Smiles OC(C(OC)=C1)=CC=C1C(O2)C(C)C3=C2C(OC)=CC(/C=C/C)=C3
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081238
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID e5793e3799874d509d1d08f5231ee5fe
##Scan# 1
#SpectrumFile gnps_LicarinA_pos_MplusH.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 327.3
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
91.075 0.57
128.026 2.43
141.019 0.87
143.032 19.76
267.102 2.42
327.1591 0.0
