>compound Erythrinine
>formula C18H19NO4
>ionization [M+H]+
>parentmass 314.13868454009054
#inchi InChI=1S/C18H19NO4/c1-21-12-3-2-11-4-5-19-9-15(20)13-6-16-17(23-10-22-16)7-14(13)18(11,19)8-12/h2-4,6-7,12,15,20H,5,8-10H2,1H3
#inchikey VBJYPSPIKMUCLP
#Ion_Source DI-ESI
#Instrument Ion Trap
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 282.1
#ExactMass 313.131
#Charge 1
#CAS_Number 29306-29-4
#Pubmed_ID  
#Smiles COC1CC23C4=CC5=C(OCO5)C=C4C(O)CN2CC=C3C=C1
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081235
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 57779211e4a54c9c8eb01d92a1f11787
##Scan# 1
#SpectrumFile gnps_Erythrinine_pos_MplusHminusCH3OH.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 282.1
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
135.043 2.17
137.048 0.32
206.036 10.47
217.028 24.24
252.076 4.38
254.092 3.57
314.1387 0.0
