>compound Cucurbitacin E
>formula C32H44O8
>ionization [M+Na]+
>parentmass 579.2928390680905
#inchi InChI=1S/C32H44O8/c1-17(33)40-27(2,3)13-12-23(36)32(9,39)25-21(35)15-29(6)22-11-10-18-19(14-20(34)26(38)28(18,4)5)31(22,8)24(37)16-30(25,29)7/h10,12-14,19,21-22,25,34-35,39H,11,15-16H2,1-9H3/b13-12+/t19?,21-,22+,25+,29+,30-,31+,32+/m1/s1
#inchikey NDYMQXYDSVBNLL
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Norberto Lopes
#Scan -1
#Precursor_MZ 579.287
#ExactMass 556.304
#Charge 1
#CAS_Number 18444-66-1
#Pubmed_ID  
#Smiles O=C(C1(C)C)C(O)=CC2C1=CC[C@]([C@@](C[C@@H](O)[C@@]3([C@@](O)(C(/C=C/C(C)(OC(C)=O)C)=O)C)[H])(C)[C@]3(C)C4)([H])[C@@]2(C)C4=O
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081267
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID af0be4ff03964a0ab2d47bca8cf85c56
##Scan# 1
#SpectrumFile gnps_CucurbitacinE_pos_MplusNa.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 579.287
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
385.196 2.81
479.2752 7.39
497.283 11.63
519.267 100.0
579.2874 215.19
