>compound Hesperetin
>formula C16H14O6
>ionization [M+H]+
>parentmass 303.08631462009055
#inchi InChI=1S/C16H14O6/c1-21-13-3-2-8(4-10(13)18)14-7-12(20)16-11(19)5-9(17)6-15(16)22-14/h2-6,14,17-19H,7H2,1H3
#inchikey AIONOLUJZLIMTK
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Commercial
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 303.077
#ExactMass 302.079
#Charge 1
#CAS_Number 69097-99-0
#Pubmed_ID  
#Smiles O=C1C2=C(O)C=C(O)C=C2OC(C3=CC=C(OC)C(O)=C3)C1
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000078875
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 30eb3d93f51f4171973eaf1a7a9d1ee3
##Scan# 1
#SpectrumFile gnps_hesperetin_pos_MSMS_303.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 303.077
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
155.0489 0.3
186.0522 1.89
303.0863 0.0
