>compound Taxifolin
>formula C15H12O7
>ionization [M+H]+
>parentmass 305.0655791760905
#inchi InChI=1S/C15H12O7/c16-7-4-10(19)12-11(5-7)22-15(14(21)13(12)20)6-1-2-8(17)9(18)3-6/h1-5,14-19,21H/t14-,15+/m0/s1
#inchikey CXQWRCVTCMQVQX
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Commercial
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 303.065
#ExactMass 304.058
#Charge 1
#CAS_Number 480-18-2
#Pubmed_ID  
#Smiles O=C1C2=C(O)C=C(O)C=C2O[C@H](C3=CC(O)=C(O)C=C3)[C@H]1O
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000078866
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID a6739e42dcec4b55ad4aa676ca80618c
##Scan# 1
#SpectrumFile taxifolin_pos_MSMS_305.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 303.065
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
121.0266 1.51
157.0629 0.95
190.0464 2.39
202.0468 0.79
305.0656 0.0
