>compound erysovine
>formula C18H21NO3
>ionization [M+H]+
>parentmass 300.1594199840905
#inchi InChI=1S/C18H21NO3/c1-21-14-4-3-13-6-8-19-7-5-12-9-17(22-2)16(20)10-15(12)18(13,19)11-14/h3-4,6,9-10,14,20H,5,7-8,11H2,1-2H3
#inchikey IHPMURIXWRKEKD
#Ion_Source DI-ESI
#Instrument Ion Trap
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 268.1
#ExactMass 299.152
#Charge 1
#CAS_Number 466-72-8
#Pubmed_ID  
#Smiles OC1=C(OC)C=C2C(C3(CC(OC)C=CC3=CC4)N4CC2)=C1
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081228
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID c6744b6286a74fceb4411aac871c4f1f
##Scan# 1
#SpectrumFile gnps_erysovine_pos_MplusHminusCH3OH.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 268.1
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
153.044 0.93
219.021 40.52
236.05 76.74
239.058 6.62
300.1594 0.0
