>compound 8-Oxoerythraline_epoxide
>formula C18H17NO5
>ionization [M+H]+
>parentmass 328.1179490960905
#inchi InChI=1S/C18H17NO5/c1-21-14-7-18-10-5-13-12(22-8-23-13)4-9(10)2-3-19(18)15(20)6-11(18)16-17(14)24-16/h4-6,14,16-17H,2-3,7-8H2,1H3
#inchikey WQOZASFQHLTUGJ
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 296.1
#ExactMass 327.111
#Charge 1
#CAS_Number 252209-69-1
#Pubmed_ID  
#Smiles O=C1C=C2C3C(O3)C(OC)CC42C5=CC6=C(OCO6)C=C5CCN41
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081225
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 01b89f375a2f46749da4b6e48417848a
##Scan# 1
#SpectrumFile gnps_8-Oxoerythraline_epoxide_pos_MplusHminusCH3OH.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 296.1
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
118.998 3.63
146.02 0.42
150.009 0.81
174.03 5.16
176.024 18.2
220.072 0.35
250.072 7.08
268.06 100.0
296.057 27.5
328.1179 0.0
