>compound Piptocarphin A
>formula C21H26O9
>ionization [M+Na]+
>parentmass 445.1469031120905
#inchi InChI=1S/C21H26O9/c1-11(2)17(23)28-15-9-20(5,25)21(26)7-6-19(4,30-21)8-14-16(15)13(18(24)29-14)10-27-12(3)22/h8,15,25-26H,1,6-7,9-10H2,2-5H3/b14-8+/t15-,19+,20+,21-/m0/s1
#inchikey BZQDHZDSIXPDSS
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Gobbo Neto
#Scan -1
#Precursor_MZ 445.14
#ExactMass 422.158
#Charge 1
#CAS_Number 76248-63-0
#Pubmed_ID N/A
#Smiles O=C1C(COC(C)=O)=C2[C@@H](OC(C(C)=C)=O)C[C@@](C)(O)[C@@](O)(O3)CC[C@]3(C)/C=C2/O1
#INCHI_AUX N/A
#Library_Class 3
#SpectrumID CCMSLIB00000081736
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 52bd5f0db6314c93924d5ce5c86348eb
##Scan# 1
#SpectrumFile gnps_PiptocarphinA_pos_MplusNa.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism batch_27_05_V02
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 445.14
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
259.0942 3.36
445.1469 0.0
