>compound 2-(5-formyl-3,4-dihydro-2,2-dimethyl-2H-pyran-6-yl)-Benzoic acid
>formula C15H14O3
>ionization [M+Na]+
>parentmass 265.0835150080905
#inchi InChI=1S/C15H14O3/c1-15(2)8-7-11-13(17)12(16)9-5-3-4-6-10(9)14(11)18-15/h3-6H,7-8H2,1-2H3
#inchikey QZPQTZZNNJUOLS
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 283.091
#ExactMass 242.094
#Charge 1
#CAS_Number 1027802-07-8
#Pubmed_ID  
#Smiles O=C(C1=CC=CC=C1C2=C3CCC(C)(C)O2)C3=O
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081244
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 90cb44284c3c436ab31eddf4ed4cc13b
##Scan# 1
#SpectrumFile gnps_2_5_formyl_3_4_dihydro_2_2_dimethyl_2H_pyran_6_yl_Benzoic_acid_pos_M_Na.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 283.091
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
121.0613 10.0
133.0254 1.52
149.0195 19.88
159.0418 21.24
173.094 4.95
207.0414 2.08
265.0835 0.0
