>compound 8-Oxoerythraline_epoxide
>formula C18H17NO5
>ionization [M+H]+
>parentmass 328.1179490960905
#inchi InChI=1S/C18H17NO5/c1-21-14-7-18-10-5-13-12(22-8-23-13)4-9(10)2-3-19(18)15(20)6-11(18)16-17(14)24-16/h4-6,14,16-17H,2-3,7-8H2,1H3
#inchikey WQOZASFQHLTUGJ
#Ion_Source DI-ESI
#Instrument Ion Trap
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 328.1
#ExactMass 327.111
#Charge 1
#CAS_Number 252209-69-1
#Pubmed_ID  
#Smiles O=C1C=C2C3C(O3)C(OC)CC42C5=CC6=C(OCO6)C=C5CCN41
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081224
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 8ab0a5d8e07644c48e096becb563e974
##Scan# 1
#SpectrumFile gnps_8-Oxoerythraline_epoxide_pos_MplusH.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 328.1
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
108.044 0.31
252.029 0.4
254.023 2.28
310.072 2.68
328.1179 0.0
