>compound Carbamimidothioic acid
>formula C3H8N2O3S2
>ionization [M+Na]+
>parentmass 206.9868548160905
#inchi InChI=1S/C3H8N2O3S2/c4-3(5)9-1-2-10(6,7)8/h1-2H2,(H3,4,5)(H,6,7,8)
#inchikey LTHWZZOUNJCHES
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Commercial
#PI Norberto Lopes
#Data_Collector Norberto Lopes
#Scan -1
#Precursor_MZ 206.982
#ExactMass 183.998
#Charge 1
#CAS_Number 25985-57-3
#Pubmed_ID N/A
#Smiles NC(SCCS(=O)(O)=O)=N
#INCHI_AUX N/A
#Library_Class 3
#SpectrumID CCMSLIB00000081563
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 4a07f16a650f4095b43fe6b0b09ff8bb
##Scan# 1
#SpectrumFile gnps_Carbamimidothioic_acid_pos_MplusNa.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism batch_27_05
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 206.982
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
130.9724 22.6
166.955 4.43
206.9869 0.0
