>compound Erythrinine
>formula C19H23NO4
>ionization [M+H]+
>parentmass 330.16998466809054
#inchi InChI=1S/C19H23NO4/c1-22-16-8-12-4-6-20-7-5-13-9-15(21)18(24-3)11-19(13,20)14(12)10-17(16)23-2/h8-10,18H,4-7,11H2,1-3H3
#inchikey GFSAAWPDCQHEAN
#Ion_Source DI-ESI
#Instrument Ion Trap
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 314.1
#ExactMass 329.163
#Charge 1
#CAS_Number  
#Pubmed_ID  
#Smiles COC1CC23C4=CC(OC)=C(OC)C=C4CCN2CCC3=CC1=O
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081234
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 9013731ef46f4325af2824f7a842f031
##Scan# 1
#SpectrumFile gnps_Erythrinine_pos_MplusH.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 314.1
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
134.997 0.44
160.016 0.43
223.028 1.51
234.054 19.76
253.12 0.6
264.076 22.81
281.079 0.77
330.17 0.0
