>compound Quercetin 3,7-dimethyl ether
>formula C17H14O7
>ionization [M+H]+
>parentmass 331.0812292400905
#inchi InChI=1S/C17H14O7/c1-22-9-6-12(20)14-13(7-9)24-16(17(23-2)15(14)21)8-3-4-10(18)11(19)5-8/h3-7,18-20H,1-2H3
#inchikey LUJAXSNNYBCFEE
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Gobbo Neto
#Scan -1
#Precursor_MZ 331.076
#ExactMass 330.074
#Charge 1
#CAS_Number 2068-02-02
#Pubmed_ID N/A
#Smiles OC1=C(O)C=C(C2=C(OC)C(C3=C(O)C=C(OC)C=C3O2)=O)C=C1
#INCHI_AUX N/A
#Library_Class 3
#SpectrumID CCMSLIB00000081737
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 52bd5f0db6314c93924d5ce5c86348eb
##Scan# 1
#SpectrumFile gnps_Quercetin_3_7_dimethyl_ether_pos_MplusH.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism batch_27_05_V02
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 331.076
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
191.0563 1.1
229.0476 1.91
331.0812 0.0
