>compound Grandisin
>formula C24H32O7
>ionization [M+H]+
>parentmass 433.2220798160905
#inchi InChI=1S/C24H32O7/c1-13-14(2)22(16-11-19(27-5)24(30-8)20(12-16)28-6)31-21(13)15-9-17(25-3)23(29-7)18(10-15)26-4/h9-14,21-22H,1-8H3/t13-,14-,21-,22-/m0/s1
#inchikey ZPINJJOPURFFNV
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 433.22
#ExactMass 432.215
#Charge 1
#CAS_Number 53250-50-3
#Pubmed_ID  
#Smiles C[C@H]1[C@H](C)[C@@H](C2=CC(OC)=C(OC)C(OC)=C2)O[C@@H]1C3=CC(OC)=C(OC)C(OC)=C3
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000078860
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID bc1995a147a7433b96f968d1e7a0c16c
##Scan# 1
#SpectrumFile grandisin_pos_MSMS_433.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 433.22
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
352.1635 1.05
369.1661 0.76
433.2221 0.0
