>compound 3',4',5',6'-tetrahydro-6',6'-dimethyl-spiro[isobenzofuran-1(3H),2'-[2H]pyran]-3-one
>formula C14H16O3
>ionization [M+Na]+
>parentmass 255.0991650720905
#inchi InChI=1S/C14H16O3/c1-13(2)8-5-9-14(17-13)11-7-4-3-6-10(11)12(15)16-14/h3-4,6-7H,5,8-9H2,1-2H3
#inchikey JYMSPANBDPOHPX
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Niege Furtado
#Scan -1
#Precursor_MZ 255.097
#ExactMass 232.11
#Charge 1
#CAS_Number 1143502-33-3
#Pubmed_ID  
#Smiles O=C1OC2(OC(C)(C)CCC2)C3=CC=CC=C31
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081252
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 1245fb93f4534765a0d841b204eca52a
##Scan# 1
#SpectrumFile gnps_3_4_5_6_tetrahydro_6_6_dimethyl_spiro_isobenzofuran_1_3H_2_2H_pyran_3_one_pos_MplusNa.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 255.097
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
131.0463 3.19
133.0266 1.56
147.0412 5.64
149.0195 27.54
159.041 25.53
175.0368 3.74
179.0821 5.58
187.0361 3.65
197.0943 7.79
255.0971 292.57
