>compound rel -Methylenedioxy-tetramethoxy-epoxylignan
>formula C23H28O7
>ionization [M+H]+
>parentmass 417.1907796880905
#inchi InChI=1S/C23H28O7/c1-12-13(2)21(15-9-18(26-5)23-19(10-15)28-11-29-23)30-20(12)14-7-16(24-3)22(27-6)17(8-14)25-4/h7-10,12-13,20-21H,11H2,1-6H3/t12-,13-,20+,21-/m0/s1
#inchikey RKSBJQZDPAGEQW
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 417.182
#ExactMass 416.184
#Charge 1
#CAS_Number 1009642-55-0
#Pubmed_ID  
#Smiles COC1=C(OC)C=C([C@H]2[C@@H](C)[C@H](C)[C@@H](C3=CC(OC)=C(OCO4)C4=C3)O2)C=C1OC
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081297
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 4289e052252b4b6b8ca74c71b842f49a
##Scan# 1
#SpectrumFile gnps_rel_7R_8S_7_S_8_S_4_5_methylenedioxy_3_4_5_3_tetramethoxy_7_7_epoxylignan_pos_MplusH.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 417.182
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
180.0562 2.55
196.0869 2.49
417.1908 0.0
