>compound Pinostrobin
>formula C16H14O4
>ionization [M+H]+
>parentmass 271.09648538009054
#inchi InChI=1S/C16H14O4/c1-19-11-7-12(17)16-13(18)9-14(20-15(16)8-11)10-5-3-2-4-6-10/h2-8,14,17H,9H2,1H3
#inchikey ORJDDOBAOGKRJV
#Ion_Source DI-ESI
#Instrument Ion Trap
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 271.0
#ExactMass 270.089
#Charge 1
#CAS_Number 75291-74-6
#Pubmed_ID  
#Smiles O=C1C2=C(C=C(C=C2OC(C1)C3=CC=CC=C3)OC)O
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000077220
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 8963493adfa441b29f0d8419732ee69d
##Scan# 1
#SpectrumFile gnps_Pinostrobin_pos_amp0.5V_MSMS_271.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 271
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
193.064 6.6
271.0965 0.0
