>compound Quercetin
>formula C15H10O7
>ionization [M+H]+
>parentmass 303.0499291120905
#inchi InChI=1S/C15H10O7/c16-7-4-10(19)12-11(5-7)22-15(14(21)13(12)20)6-1-2-8(17)9(18)3-6/h1-5,16-19,21H
#inchikey REFJWTPEDVJJIY
#Ion_Source DI-ESI
#Instrument Ion Trap
#Compound_Source Commercial
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 303.0
#ExactMass 302.043
#Charge 1
#CAS_Number 117-39-5
#Pubmed_ID  
#Smiles O=C1C2=C(C=C(C=C2OC(C3=CC(O)=C(C=C3)O)=C1O)O)O
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000077993
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 900e881400954b2889fd7248945e46b9
##Scan# 1
#SpectrumFile gnps_Quercetin_pos_amp0.7V_MSMS_303.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 303
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
121.049 2.07
212.031 4.59
303.0499 0.0
