>compound Duguetine ??-N-oxide
>formula C20H21NO6
>ionization [M+H]+
>parentmass 372.1441638440906
#inchi InChI=1S/C20H21NO6/c1-21(23)5-4-10-6-15-20(27-9-26-15)17-11-7-13(24-2)14(25-3)8-12(11)19(22)18(21)16(10)17/h6-8,18-19,22H,4-5,9H2,1-3H3/t18-,19-,21+/m0/s1
#inchikey XKKFNYKNDDHAQC
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 372.111
#ExactMass 371.137
#Charge 1
#CAS_Number 374106-25-9
#Pubmed_ID N/A
#Smiles COC1=C(OC)C=C([C@@](O)([H])[C@]2([H])C3=C4C5=C(OCO5)C=C3CC[N@+]2([O-])C)C4=C1
#INCHI_AUX N/A
#Library_Class 3
#SpectrumID CCMSLIB00000081686
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 52bd5f0db6314c93924d5ce5c86348eb
##Scan# 1
#SpectrumFile gnps_Duguetine_beta_N_oxide_pos_MplusH.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism batch_27_05_V02
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 372.111
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
236.0604 0.6
251.0489 0.77
252.0567 0.66
264.0521 0.56
277.0604 0.57
372.1442 0.0
