>compound Morin
>formula C15H10O7
>ionization [M+H]+
>parentmass 303.0499291120905
#inchi InChI=1S/C15H10O7/c16-6-1-2-8(9(18)3-6)15-14(21)13(20)12-10(19)4-7(17)5-11(12)22-15/h1-5,16-19,21H
#inchikey YXOLAZRVSSWPPT
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 303.043
#ExactMass 302.043
#Charge 1
#CAS_Number 480-16-0
#Pubmed_ID  
#Smiles O=C1C2=C(O)C=C(O)C=C2OC(C3=C(O)C=C(O)C=C3)=C1O
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000078879
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 0dbf2d4c4eab4c8f8176c027d3127378
##Scan# 1
#SpectrumFile gnps_morin_pos_MSMS_303.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 303.043
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
155.0509 1.1
183.0237 21.31
184.0301 1.36
303.0499 0.0
