>compound 7-O-methyl_ galangin
>formula C16H12O5
>ionization [M+H]+
>parentmass 285.0757499360905
#inchi InChI=1S/C16H12O5/c1-20-10-7-11(17)13-12(8-10)21-16(15(19)14(13)18)9-5-3-2-4-6-9/h2-8,17,19H,1H3
#inchikey PVJNLMXWZXXHSZ
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 285.071
#ExactMass 284.069
#Charge 1
#CAS_Number 480-14-8
#Pubmed_ID  
#Smiles O=C1C2=C(O)C=C(OC)C=C2OC(C3=CC=CC=C3)=C1O
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000078845
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 191d51d1f6c4461e891d4dc0d5f2ef91
##Scan# 1
#SpectrumFile 7_methyl_galangin_pos_MSMS_285.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 285.071
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
131.0472 2.37
285.0757 0.0
