>compound Swertisin
>formula C22H22O10
>ionization [M+H]+
>parentmass 447.13
#inchi InChI=1S/C22H22O10/c1-30-13-7-14-16(11(25)6-12(31-14)9-2-4-10(24)5-3-9)19(27)17(13)22-21(29)20(28)18(26)15(8-23)32-22/h2-7,15,18,20-24,26-29H,8H2,1H3/t15-,18-,20+,21-,22+/m1/s1
#inchikey ABRULANJVVJLFI
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 447.13
#ExactMass 446.121
#Charge 1
#CAS_Number 6991-10-2
#Pubmed_ID  
#Smiles OC1=CC=C(C=C1)C2=CC(C3=C(C([C@@H]4O[C@@H]([C@H]([C@@H]([C@H]4O)O)O)CO)=C(C=C3O2)OC)O)=O
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000078881
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 03df2bdeb1eb422b8b4aa95f3a4855b0
##Scan# 1
#SpectrumFile gnps_swertisin_pos_MSMS_447.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 447.13
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
393.0845 14.43
447.13 0.0
