>compound Crystamidine
>formula C18H15NO4
>ionization [M+H]+
>parentmass 310.10738441209054
#inchi InChI=1S/C18H15NO4/c1-21-13-3-2-12-7-17(20)19-5-4-11-6-15-16(23-10-22-15)8-14(11)18(12,19)9-13/h2-8,13H,9-10H2,1H3
#inchikey NZMLLYZLUYBOGO
#Ion_Source DI-ESI
#Instrument Ion Trap
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 278.1
#ExactMass 309.1
#Charge 1
#CAS_Number 58779-39-8
#Pubmed_ID  
#Smiles O=C1C=C2C=CC(OC)CC32C4=CC5=C(OCO5)C=C4C=CN31
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081237
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 6a00ce712e61403c8643d54fe8b1ee61
##Scan# 1
#SpectrumFile gnps_Crystamidine_pos_MplusHminusCH3OH.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 278.1
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
232.073 1.07
310.1074 0.0
