>compound Techtochrysin
>formula C16H12O4
>ionization [M+H]+
>parentmass 269.08083531609054
#inchi InChI=1S/C16H12O4/c1-19-11-7-12(17)16-13(18)9-14(20-15(16)8-11)10-5-3-2-4-6-10/h2-9,17H,1H3
#inchikey IRZVHDLBAYNPCT
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 269.073
#ExactMass 268.074
#Charge 1
#CAS_Number 520-28-5
#Pubmed_ID  
#Smiles O=C1C2=C(O)C=C(OC)C=C2OC(C3=CC=CC=C3)=C1
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081300
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 265d063d48ff46279939c81a720db552
##Scan# 1
#SpectrumFile gnps_Techtochrysin_pos_MplusH.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 269.073
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
155.0475 3.23
179.0503 3.41
269.0808 0.0
