>compound Sinapinic acid
>formula C11H12O5
>ionization [M+H]+
>parentmass 225.07574993609052
#inchi InChI=1S/C11H12O5/c1-15-8-5-7(3-4-10(12)13)6-9(16-2)11(8)14/h3-6,14H,1-2H3,(H,12,13)/b4-3+
#inchikey PCMORTLOPMLEFB
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Commercial
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 225.08
#ExactMass 224.068
#Charge 1
#CAS_Number 530-59-6
#Pubmed_ID  
#Smiles OC(/C=C/C1=CC(OC)=C(O)C(OC)=C1)=O
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000078855
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 51daf0954ab44ee9b2bfeb804978a957
##Scan# 1
#SpectrumFile sinapinic_acid_pos_MSMS_225.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 225.08
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
117.0318 1.06
121.0267 2.7
170.0567 0.4
173.0228 1.94
188.0661 0.51
225.0757 0.0
