>compound Glaucolide A
>formula C23H28O10
>ionization [M+Na]+
>parentmass 487.1574677960905
#inchi InChI=1S/C23H28O10/c1-11(2)20(27)30-15-9-23(6,32-13(4)25)16(26)7-8-22(5)19(33-22)18-17(15)14(21(28)31-18)10-29-12(3)24/h15,18-19H,1,7-10H2,2-6H3/t15-,18-,19+,22+,23+/m0/s1
#inchikey DDRDDFBLSIAXPP
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 487.15
#ExactMass 464.168
#Charge 1
#CAS_Number 11091-29-5
#Pubmed_ID N/A
#Smiles O=C(C)OCC1=C([C@@H](OC(C(C)=C)=O)C[C@]2(OC(C)=O)C)[C@@](OC1=O)([H])[C@@H]3[C@@](O3)(C)CCC2=O
#INCHI_AUX N/A
#Library_Class 3
#SpectrumID CCMSLIB00000081474
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 053e8682627d4c9488a292c234ed8aed
##Scan# 1
#SpectrumFile gnps_GlaucolideA_pos_MplusNa.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism blank
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 487.15
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
277.0992 86.28
299.0819 12.37
313.0982 13.53
319.1106 28.99
487.1575 0.0
