>compound 3',4',5',6'-tetrahydro-6',6'-dimethyl-spiro[isobenzofuran-1(3H),2'-[2H]pyran]-3-one
>formula C14H16O3
>ionization [M+H]+
>parentmass 233.115234
#inchi InChI=1S/C14H16O3/c1-13(2)8-5-9-14(17-13)11-7-4-3-6-10(11)12(15)16-14/h3-4,6-7H,5,8-9H2,1-2H3
#inchikey JYMSPANBDPOHPX
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Niege Furtado
#Scan -1
#Precursor_MZ 233.115
#ExactMass 232.11
#Charge 1
#CAS_Number 1143502-33-3
#Pubmed_ID  
#Smiles O=C1OC2(OC(C)(C)CCC2)C3=CC=CC=C31
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081251
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 01b102dc1e3746d98bc5a49952f41e9c
##Scan# 1
#SpectrumFile gnps_3_4_5_6_tetrahydro_6_6_dimethyl_spiro_isobenzofuran_1_3H_2_2H_pyran_3_one_pos_M_H.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 233.115
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
197.0941 48.58
233.1152 18.32
