>compound Rosmarinic acid
>formula C18H16O8
>ionization [M+H]+
>parentmass 361.09
#inchi InChI=1S/C18H16O8/c19-12-4-1-10(7-14(12)21)3-6-17(23)26-16(18(24)25)9-11-2-5-13(20)15(22)8-11/h1-8,16,19-22H,9H2,(H,24,25)/b6-3+
#inchikey DOUMFZQKYFQNTF
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Commercial
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 361.09
#ExactMass 360.085
#Charge 1
#CAS_Number 20283-92-5
#Pubmed_ID  
#Smiles O=C(OC(C(O)=O)CC1=CC(O)=C(O)C=C1)/C=C/C2=CC(O)=C(O)C=C2
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000078853
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 64bd9a924f8a422395503fd448c6ec3d
##Scan# 1
#SpectrumFile rosmarinic_acid_pos_MSMS_361.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 361.09
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
117.0319 4.44
181.0487 0.73
186.0529 9.74
361.09 0.0
