>compound 6-Benzyladenine
>formula C12H11N5
>ionization [M+H]+
>parentmass 226.108887
#inchi InChI=1S/C12H11N5/c1-2-4-9(5-3-1)6-13-11-10-12(15-7-14-10)17-8-16-11/h1-5,7-8H,6H2,(H2,13,14,15,16,17)
#inchikey NWBJYWHLCVSVIJ
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Commercial
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 226.109
#ExactMass 225.101
#Charge 1
#CAS_Number 1214-39-7
#Pubmed_ID  
#Smiles C12=NC=NC(NCC3=CC=CC=C3)=C1NC=N2
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081271
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 996f8b2ae88f4daabefb1f2aaaa2b1c0
##Scan# 1
#SpectrumFile gnps_6_Benzyladenine_pos_MplusH.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 226.109
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
119.0355 45.12
121.0506 18.68
130.0666 14.15
140.0497 1.66
148.0627 100.0
155.0606 2.94
157.078 10.85
184.0886 6.14
226.1089 18.25
