>compound 8-Oxoerythraline
>formula C18H17NO4
>ionization [M+H]+
>parentmass 312.12303447609054
#inchi InChI=1S/C18H17NO4/c1-21-13-3-2-12-7-17(20)19-5-4-11-6-15-16(23-10-22-15)8-14(11)18(12,19)9-13/h2-3,6-8,13H,4-5,9-10H2,1H3
#inchikey RNCIERMYMLFYAO
#Ion_Source DI-ESI
#Instrument Ion Trap
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 280.1
#ExactMass 311.116
#Charge 1
#CAS_Number 58779-40-1
#Pubmed_ID  
#Smiles COC(C=CC1=C2)CC31C4=CC5=C(OCO5)C=C4CCN3C2=O
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081223
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 81fcde4ed05748f6804df55524bf6977
##Scan# 1
#SpectrumFile gnps_8-Oxoerythraline_posMplusHminusCH3OH.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 280.1
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
132.045 0.5
146.015 0.44
179.012 0.64
252.076 2.56
312.123 0.0
