>compound Erythraline
>formula C18H19NO3
>ionization [M+H]+
>parentmass 298.1437699200905
#inchi InChI=1S/C18H19NO3/c1-20-14-3-2-13-5-7-19-6-4-12-8-16-17(22-11-21-16)9-15(12)18(13,19)10-14/h2-3,5,8-9,14H,4,6-7,10-11H2,1H3
#inchikey TVOFUERNMZTYRM
#Ion_Source DI-ESI
#Instrument Ion Trap
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 266.0
#ExactMass 297.137
#Charge 1
#CAS_Number 466-77-3
#Pubmed_ID  
#Smiles COC1CC23C4=CC5=C(OCO5)C=C4CCN2CC=C3C=C1
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081230
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 154365ea5c3e4e9b8284f01c0eafd792
##Scan# 1
#SpectrumFile gnps_Erythraline_pos_MplusHminusCH3OH.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 266
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
176.013 0.56
203.048 0.55
224.035 1.49
236.071 43.93
249.055 100.0
264.068 14.78
298.1438 0.0
