>compound Galangin
>formula C15H10O5
>ionization [M+H]+
>parentmass 271.0600998720905
#inchi InChI=1S/C15H10O5/c16-9-6-10(17)12-11(7-9)20-15(14(19)13(12)18)8-4-2-1-3-5-8/h1-7,16-17,19H
#inchikey VCCRNZQBSJXYJD
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 271.053
#ExactMass 270.053
#Charge 1
#CAS_Number 548-83-4
#Pubmed_ID  
#Smiles O=C1C2=C(O)C=C(O)C=C2OC(C3=CC=CC=C3)=C1O
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000078874
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 0792de2ddbbb47679b42145ad0f7ebf8
##Scan# 1
#SpectrumFile gnps_galangin_pos_MSMS_271.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 271.053
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
150.0331 1.05
155.0479 7.91
179.0474 3.17
271.0601 0.0
