>compound Ellagic acid
>formula C14H6O8
>ionization [M+H]+
>parentmass 303.0135436040905
#inchi InChI=1S/C14H6O8/c15-5-1-3-7-8-4(14(20)22-11(7)9(5)17)2-6(16)10(18)12(8)21-13(3)19/h1-2,15-18H
#inchikey AFSDNFLWKVMVRB
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Commercial
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 303.01
#ExactMass 302.006
#Charge 1
#CAS_Number  
#Pubmed_ID  
#Smiles OC1=C(O)C2=C(C(C3=C(O)C(O)=C4)=C4C(O2)=O)C(C(O3)=O)=C1
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000078849
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID efbcfcf188ad467482697c377c870313
##Scan# 1
#SpectrumFile ellagic_acid_pos_MSMS_303.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 303.01
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
201.0181 23.84
285.0007 74.45
303.0135 0.0
