>compound (2S,3S,4R,6S)-2-((6-hydroxy-2,2-dimethyl-3,4-dihydro-2H-benzo[h]chromen-5-yl)oxy)-6-(hydroxymethyl)tetrahydro-2H-pyran-3,4,5-triol
>formula C21H26O8
>ionization [M+H]+
>parentmass 407.1700442440905
#inchi InChI=1S/C21H26O8/c1-21(2)8-7-12-18(29-21)11-6-4-3-5-10(11)14(23)19(12)28-20-17(26)16(25)15(24)13(9-22)27-20/h3-6,13,15-17,20,22-26H,7-9H2,1-2H3/t13-,15?,16+,17-,20-/m0/s1
#inchikey CGYNVHQAIUIQLZ
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Niege Furtado
#Scan -1
#Precursor_MZ 245.12
#ExactMass 406.163
#Charge 1
#CAS_Number  
#Pubmed_ID  
#Smiles CC(CC1)(C)OC2=C1C(O[C@@H]3O[C@@H](CO)C(O)[C@@H](O)[C@@H]3O)=C(O)C4=CC=CC=C42
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081258
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 7b890107bacb47d08bcec8b541bc1c5b
##Scan# 1
#SpectrumFile gnps_2S_3S_4R_6S_2_6_hydroxy_2_2_dimethyl_3_4_dihydro_2H_benzo_h_chromen_5_yl_oxy_6_hydroxymethyl_tetrahydro_2H_pyran_3_4_5_triol_pos_MplusHminus162.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 245.12
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
155.0473 3.14
173.0578 2.09
187.0374 100.0
199.0742 2.3
243.0999 11.4
407.17 0.0
