>compound Apigenin
>formula C15H10O5
>ionization [M+H]+
>parentmass 271.0600998720905
#inchi InChI=1S/C15H10O5/c16-9-3-1-8(2-4-9)13-7-12(19)15-11(18)5-10(17)6-14(15)20-13/h1-7,16-18H
#inchikey KZNIFHPLKGYRTM
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 271.055
#ExactMass 270.053
#Charge 1
#CAS_Number 520-36-5
#Pubmed_ID  
#Smiles O=C1C2=C(O)C=C(O)C=C2OC(C3=CC=C(O)C=C3)=C1
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000078869
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 847659d05c8443009f260856b14364b1
##Scan# 1
#SpectrumFile gnps_apigenin_pos_MSMS_271.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 271.055
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
119.0473 13.69
121.0266 9.47
135.0223 0.69
271.0601 0.0
