>compound Caffeine
>formula C8H10N4O2
>ionization [M+H]+
>parentmass 195.08765201209053
#inchi InChI=1S/C8H10N4O2/c1-10-4-9-6-5(10)7(13)12(3)8(14)11(6)2/h4H,1-3H3
#inchikey RYYVLZVUVIJVGH
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Commercial
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 195.096
#ExactMass 194.08
#Charge 1
#CAS_Number 1958-08-02
#Pubmed_ID  
#Smiles CN1C(N(C)C(N=CN2C)=C2C1=O)=O
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000078857
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 8e932b828f214876877bec9c0378af0f
##Scan# 1
#SpectrumFile caffeine_pos_MSMS_195.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 195.096
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
122.0704 0.82
123.046 100.0
124.0488 4.22
136.0744 2.68
139.0737 3.89
195.0877 0.0
