>compound Procyanidin B2
>formula C30H26O12
>ionization [M+Na]+
>parentmass 601.1316469720905
#inchi InChI=1S/C30H26O12/c31-13-7-20(37)24-23(8-13)41-29(12-2-4-16(33)19(36)6-12)27(40)26(24)25-21(38)10-17(34)14-9-22(39)28(42-30(14)25)11-1-3-15(32)18(35)5-11/h1-8,10,22,26-29,31-40H,9H2/t22-,26-,27-,28-,29-/m1/s1
#inchikey XFZJEEAOWLFHDH
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 601.089
#ExactMass 578.142
#Charge 1
#CAS_Number 29106-49-8
#Pubmed_ID N/A
#Smiles O[C@@H]([C@@H](C1=CC=C(O)C(O)=C1)O2)CC3=C2C([C@@H]4[C@@H](O)[C@@H](C5=CC=C(O)C(O)=C5)OC6=C4C(O)=CC(O)=C6)=C(O)C=C3O
#INCHI_AUX N/A
#Library_Class 3
#SpectrumID CCMSLIB00000081690
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 52bd5f0db6314c93924d5ce5c86348eb
##Scan# 1
#SpectrumFile gnps_ProcyanidinB2_pos_MplusNa.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism batch_27_05_V02
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 601.089
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
269.0209 7.4
297.0147 11.66
311.029 100.0
323.0292 9.53
431.0404 17.53
601.1316 0.0
