>compound 2-(5-formyl-3,4-dihydro-2,2-dimethyl-2H-pyran-6-yl)-Benzoic acid
>formula C15H16O4
>ionization [M+H]+
>parentmass 261.11213544409054
#inchi InChI=1S/C15H16O4/c1-15(2)8-7-10(9-16)13(19-15)11-5-3-4-6-12(11)14(17)18/h3-6,9H,7-8H2,1-2H3,(H,17,18)
#inchikey PRIHHXHWVNIQPJ
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 261.11
#ExactMass 260.105
#Charge 1
#CAS_Number 1027802-07-8
#Pubmed_ID  
#Smiles OC(C1=C(C2=C(C([H])=O)CCC(C)(C)O2)C=CC=C1)=O
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000081243
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 7a072166e69b4adea81f66c47aa39cc4
##Scan# 1
#SpectrumFile gnps_2_5_formyl_3_4_dihydro_2_2_dimethyl_2H_pyran_6_yl_Benzoic_acid_pos_M_H.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 261.11
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
131.0474 0.69
210.0655 1.86
225.0891 4.95
261.1121 0.0
