>compound 4???-O-??-(6???-trans-p-coumaroyl)-glucopyranosyl okanin
>formula C30H28O13
>ionization [M+H]+
>parentmass 597.1602674080905
#inchi InChI=1S/C30H28O13/c31-17-6-1-15(2-7-17)5-12-24(35)41-14-23-27(38)28(39)29(40)30(43-23)42-22-11-8-18(25(36)26(22)37)19(32)9-3-16-4-10-20(33)21(34)13-16/h1-13,23,27-31,33-34,36-40H,14H2/b9-3+,12-5+/t23-,27-,28+,29-,30-/m1/s1
#inchikey SJGXLSYEYLGFRT
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 597.12
#ExactMass 596.153
#Charge 1
#CAS_Number 115070-75-2
#Pubmed_ID N/A
#Smiles O=C(/C=C/C1=CC(O)=C(O)C=C1)C2=C(O)C(O)=C(O[C@H]3[C@H](O)[C@@H](O)[C@H](O)[C@@H](COC(/C=C/C4=CC=C(O)C=C4)=O)O3)C=C2
#INCHI_AUX N/A
#Library_Class 3
#SpectrumID CCMSLIB00000081705
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 52bd5f0db6314c93924d5ce5c86348eb
##Scan# 1
#SpectrumFile gnps_4_O_beta_6_trans_p_coumaroyl_glucopyranosyl_okanin_pos_MplusH.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism batch_27_05_V02
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 597.12
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
147.0305 100.0
163.024 1.58
165.0379 5.02
289.0424 29.21
597.1603 0.0
