>compound Quinic acid
>formula C7H12O6
>ionization [M+H]+
>parentmass 193.069946
#inchi InChI=1S/C7H12O6/c8-3-1-7(13,6(11)12)2-4(9)5(3)10/h3-5,8-10,13H,1-2H2,(H,11,12)/t3-,4-,5-,7+/m0/s1
#inchikey AAWZDTNXLSGCEK
#Ion_Source DI-ESI
#Instrument qTof
#Compound_Source Isolated
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 193.07
#ExactMass 192.063
#Charge 1
#CAS_Number 36413-60-2
#Pubmed_ID N/A
#Smiles O[C@@]1(C(O)=O)C[C@H](O)[C@@H](O)[C@@H](O)C1
#INCHI_AUX N/A
#Library_Class 3
#SpectrumID CCMSLIB00000081718
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 52bd5f0db6314c93924d5ce5c86348eb
##Scan# 1
#SpectrumFile gnps_Quinic_acid_pos_MplusH.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism batch_27_05_V02
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 193.07
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
147.0634 79.22
157.0481 100.0
175.0591 8.6
193.0699 46.01
