>compound Homoeriodictyol
>formula C16H14O6
>ionization [M+H]+
>parentmass 303.08631462009055
#inchi InChI=1S/C16H14O6/c1-21-14-4-8(2-3-10(14)18)13-7-12(20)16-11(19)5-9(17)6-15(16)22-13/h2-6,13,17-19H,7H2,1H3
#inchikey FTODBIPDTXRIGS
#Ion_Source DI-ESI
#Instrument Ion Trap
#Compound_Source Commercial
#PI Norberto Lopes
#Data_Collector Denise Silva
#Scan -1
#Precursor_MZ 303.0
#ExactMass 302.079
#Charge 1
#CAS_Number 446-71-9
#Pubmed_ID  
#Smiles O=C1C2=C(C=C(C=C2OC(C1)C3=CC=C(C(OC)=C3)O)O)O
#INCHI_AUX  
#Library_Class 3
#SpectrumID CCMSLIB00000077213
#IonMode Positive
#UpdateWorkflowName UPDATE-SINGLE-ANNOTATED-BRONZE
#LibraryQualityString Bronze
#TaskID 4c80801f0a4f44d9864351eac9aafa4a
##Scan# 1
#SpectrumFile gnps_homoeriodictyol_pos_amp0.5V_MSMS_303.mgf
#LibraryName gnps_library.mgf
#MQScore -1
#Organism gnps_library
#TIC_Query 0
#RT_Query -1
#MZErrorPPM -1
#SharedPeaks 0
#MassDiff 0
#LibMZ -1
#SpecMZ 303
#SpecCharge 0
#internalFilename spec-00000.mgf

>collision 0
117.055 2.2
166.997 40.09
253.072 2.21
303.0863 0.0
